# Generated by Django 3.2 on 2021-05-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=600)),
                ('address', models.CharField(max_length=600)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('desc', models.TextField()),
                ('industry', models.CharField(choices=[('', 'Wybierz branżę'), ('mt', 'Motoryzacja'), ('bt', 'Beauty'), ('md', 'Medyczna'), ('up', 'Usługi Prawnicze')], default='', max_length=2)),
            ],
        ),
    ]
